const tasksData = [
  {
    id: 1,
    title: "Task 1",
    description: "Description of Task 1",
    startDate: "2024-03-20",
    endDate: "2024-03-28",
    status: "Completed",
    assignee: "John Doe",
    priority: "P1",
  },
  {
    id: 2,
    title: "Task 2",
    description: "Description of Task 2",
    startDate: "2024-03-15",
    endDate: "2024-03-25",
    status: "Completed",
    assignee: "Jane Smith",
    priority: "P2",
  },
  {
    id: 3,
    title: "Task 3",
    description: "Description of Task 3",
    startDate: "2024-03-18",
    endDate: null,
    status: "In Progress",
    assignee: "Alice Johnson",
    priority: "P0",
  },
  {
    id: 4,
    title: "Task 4",
    description: "Description of Task 4",
    startDate: "2024-03-22",
    endDate: null,
    status: "Deferred",
    assignee: "Bob Brown",
    priority: "P1",
  },
  {
    id: 5,
    title: "Task 5",
    description: "Description of Task 5",
    startDate: "2024-03-19",
    endDate: null,
    status: "Pending",
    assignee: "John Doe",
    priority: "P2",
  },
  {
    id: 6,
    title: "Task 6",
    description: "Description of Task 6",
    startDate: "2024-03-23",
    endDate: null,
    status: "Deployed",
    assignee: "Alice Johnson",
    priority: "P1",
  },
  {
    id: 7,
    title: "Task 7",
    description: "Description of Task 7",
    startDate: "2024-03-17",
    endDate: null,
    status: "Pending",
    assignee: "Bob Brown",
    priority: "P0",
  },
];

export default tasksData;
